[package]
name = "russcip"
authors = ["Mohammad Ghannam <mohammad.m.ghannam@gmail.com>"]
description = "Rust interface for SCIP."
license = "Apache-2.0"
repository = "https://github.com/mmghannam/russcip"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.60.1"
cc = "1.0.73"